### ISSUE TITLE
Day 4:

### ISSUE THREAD

**Issue by Doozers** [PoCInnovation/Pool2023#26]
- [ ] define truffle or hardhat ?

## Tasks: 
- [ ] task init project
- [ ] task deploy NFT contract
- [ ] task connect metamask
- [ ] task interact with contract on webapp
- [ ] task use event in the app
